// 动态加载 src/assets/providers 下所有图标
const iconModules = import.meta.glob<string>("@/assets/providers/*.{webp,png}", {
  eager: true,
  query: "?url",
  import: "default",
});

/** 从本地 assets/providers 获取图标 URL */
function icon(id: string): string {
  for (const [key, url] of Object.entries(iconModules)) {
    const filename = key.split("/").pop()?.split(".")[0];
    if (filename === id) return url;
  }
  return "";
}

export const providersLogo: Record<string, string> = {
  deepSeek: icon("deepseek"),
  volcengine: icon("volcengine"),
  kling: icon("kling"),
  zhipu: icon("zhipu"),
  qwen: icon("qwen"),
  wan: icon("qwen"),
  openai: icon("openai"),
  vidu: icon("vidu"),
  anthropic: icon("anthropic"),
  claude: icon("claude"),
  runninghub: icon("runninghub"),
  gemini: icon("gemini"),
  google: icon("google"),
  xai: icon("xai"),
  grok: icon("grok"),
  grsai: icon("grsai"),
  minimax: icon("minimax"),
  baichuan: icon("baichuan"),
  yi: icon("yi"),
  moonshot: icon("moonshot"),
  kimi: icon("kimi"),
  stepfun: icon("stepfun"),
  spark: icon("spark"),
  hunyuan: icon("hunyuan"),
  wenxin: icon("wenxin"),
  doubao: icon("doubao"),
  mistral: icon("mistral"),
  meta: icon("meta"),
  cohere: icon("cohere"),
  perplexity: icon("perplexity"),
  stability: icon("stability"),
  luma: icon("luma"),
  runway: icon("runway"),
  pika: icon("pika"),
  sora: icon("sora"),
  flux: icon("flux"),
  midjourney: icon("midjourney"),
  suno: icon("suno"),
  hailuo: icon("hailuo"),
  pixverse: icon("pixverse"),
  jimeng: icon("jimeng"),
  nvidia: icon("nvidia"),
  groq: icon("groq"),
  recraft: icon("recraft"),
  siliconcloud: icon("siliconcloud"),
  ideogram: icon("ideogram"),
  novita: icon("novita"),
  // 新增
  together: icon("together"),
  fireworks: icon("fireworks"),
  replicate: icon("replicate"),
  ollama: icon("ollama"),
  openrouter: icon("openrouter"),
  huggingface: icon("huggingface"),
  aws: icon("aws"),
  azure: icon("azure"),
  lambda: icon("lambda"),
  cerebras: icon("cerebras"),
  sambanova: icon("sambanova"),
  deepinfra: icon("deepinfra"),
  fal: icon("fal"),
  elevenlabs: icon("elevenlabs"),
  haiper: icon("haiper"),
  viggle: icon("viggle"),
  tripo: icon("tripo"),
  sensenova: icon("sensenova"),
  tiangong: icon("tiangong"),
  skywork: icon("skywork"),
  internlm: icon("internlm"),
  jina: icon("jina"),
  voyage: icon("voyage"),
  coze: icon("coze"),
  dify: icon("dify"),
  nanobanana: icon("nanobanana"),
  ai21: icon("ai21"),
  ai360: icon("ai360"),
  bedrock: icon("bedrock"),
  chatglm: icon("chatglm"),
  dalle: icon("dalle"),
  gemma: icon("gemma"),
  rwkv: icon("rwkv"),
  nova: icon("nova"),
  vertexai: icon("vertexai"),
  cloudflare: icon("cloudflare"),
  nebius: icon("nebius"),
  hyperbolic: icon("hyperbolic"),
  inception: icon("inception"),
  leptonai: icon("leptonai"),
  friendli: icon("friendli"),
  featherless: icon("featherless"),
  centml: icon("centml"),
  crusoe: icon("crusoe"),
  parasail: icon("parasail"),
  upstage: icon("upstage"),
  tii: icon("tii"),
  snowflake: icon("snowflake"),
  inflection: icon("inflection"),
  deepcogito: icon("deepcogito"),
  alephalpha: icon("alephalpha"),
  nousresearch: icon("nousresearch"),
  dolphin: icon("dolphin"),
  dbrx: icon("dbrx"),
  kolors: icon("kolors"),
  lightricks: icon("lightricks"),
  novelai: icon("novelai"),
  fishaudio: icon("fishaudio"),
  coqui: icon("coqui"),
  comfyui: icon("comfyui"),
  automatic: icon("automatic"),
  civitai: icon("civitai"),
  modelscope: icon("modelscope"),
  bailian: icon("bailian"),
  xinference: icon("xinference"),
  vllm: icon("vllm"),
  lmstudio: icon("lmstudio"),
  baseten: icon("baseten"),
  // 补齐
  aya: icon("aya"),
  azureai: icon("azureai"),
  baidu: icon("baidu"),
  bfl: icon("bfl"),
  briaai: icon("briaai"),
  burncloud: icon("burncloud"),
  deepai: icon("deepai"),
  deepmind: icon("deepmind"),
  essentialai: icon("essentialai"),
  glmv: icon("glmv"),
  googlecloud: icon("googlecloud"),
  hedra: icon("hedra"),
  iflytekcloud: icon("iflytekcloud"),
  infermatic: icon("infermatic"),
  infinigence: icon("infinigence"),
  kwaikat: icon("kwaikat"),
  kwaipilot: icon("kwaipilot"),
  llava: icon("llava"),
  llmapi: icon("llmapi"),
  longcat: icon("longcat"),
  lovart: icon("lovart"),
  monica: icon("monica"),
  morph: icon("morph"),
  myshell: icon("myshell"),
  openchat: icon("openchat"),
  openwebui: icon("openwebui"),
  palm: icon("palm"),
  phind: icon("phind"),
  player2: icon("player2"),
  poe: icon("poe"),
  pollinations: icon("pollinations"),
  ppio: icon("ppio"),
  qingyan: icon("qingyan"),
  sophnet: icon("sophnet"),
  statecloud: icon("statecloud"),
  straico: icon("straico"),
  streamlake: icon("streamlake"),
  submodel: icon("submodel"),
  sync: icon("sync"),
  targon: icon("targon"),
  topazlabs: icon("topazlabs"),
  turix: icon("turix"),
  udio: icon("udio"),
  workersai: icon("workersai"),
  xiaomimimo: icon("xiaomimimo"),
  xuanyuan: icon("xuanyuan"),
  yandex: icon("yandex"),
  yuanbao: icon("yuanbao"),
  zeroone: icon("zeroone"),
  newapi: icon("newapi"),
  nplcloud: icon("nplcloud"),
};

export const modelProviderRules: Array<{ pattern: RegExp; provider: keyof typeof providersLogo }> = [
  { pattern: /gpt|o1|o3|o4|openai/i, provider: "openai" },
  { pattern: /claude|anthropic/i, provider: "anthropic" },
  { pattern: /deep[-_ ]?[-_ ]?seek/i, provider: "deepSeek" },
  { pattern: /gemini|veo/i, provider: "gemini" },
  { pattern: /qwen|qwq|tongyi|通义|wanx|万相|wan/i, provider: "qwen" },
  { pattern: /cog[-_ ]?view|cog[-_ ]?video|glm|zhipu|智谱/i, provider: "zhipu" },
  { pattern: /doubao|see[-_ ]?dream|see[-_ ]?dance|volc/i, provider: "volcengine" },
  { pattern: /kling|可灵/i, provider: "kling" },
  { pattern: /vidu/i, provider: "vidu" },
  { pattern: /running[-_ ]?hub/i, provider: "runninghub" },
  { pattern: /grok|xai|grs[-_ ]?ai/i, provider: "grsai" },
  { pattern: /mini[-_ ]?max|abab|hai[-_ ]?luo|海螺/i, provider: "minimax" },
  { pattern: /bai[-_ ]?chuan|百川/i, provider: "baichuan" },
  { pattern: /\byi\b|零一|yi-/i, provider: "yi" },
  { pattern: /moon[-_ ]?shot|kimi|月之暗面/i, provider: "moonshot" },
  { pattern: /step[-_ ]?fun|阶跃/i, provider: "stepfun" },
  { pattern: /spark|星火|讯飞/i, provider: "spark" },
  { pattern: /hun[-_ ]?yuan|混元|腾讯/i, provider: "hunyuan" },
  { pattern: /ernie|文心|wen[-_ ]?xin/i, provider: "wenxin" },
  { pattern: /mistral|mixtral|pixtral|codestral/i, provider: "mistral" },
  { pattern: /llama|meta/i, provider: "meta" },
  { pattern: /cohere|command[-_ ]?r/i, provider: "cohere" },
  { pattern: /perplexity|sonar/i, provider: "perplexity" },
  { pattern: /stable[-_ .]?diffusion|stability|sdxl|sd3/i, provider: "stability" },
  { pattern: /luma|dream[-_ .]?machine/i, provider: "luma" },
  { pattern: /runway|gen-[23]/i, provider: "runway" },
  { pattern: /pika/i, provider: "pika" },
  { pattern: /sora/i, provider: "sora" },
  { pattern: /flux/i, provider: "flux" },
  { pattern: /mid[-_ ]?journey|mj/i, provider: "midjourney" },
  { pattern: /suno/i, provider: "suno" },
  { pattern: /pix[-_ ]?verse/i, provider: "pixverse" },
  { pattern: /jimeng|即梦/i, provider: "jimeng" },
  { pattern: /nvidia|nemotron/i, provider: "nvidia" },
  { pattern: /groq/i, provider: "groq" },
  { pattern: /recraft/i, provider: "recraft" },
  { pattern: /silicon[-_ ]?cloud|silicon[-_ ]?flow|硅基/i, provider: "siliconcloud" },
  { pattern: /ideogram/i, provider: "ideogram" },
  { pattern: /novita/i, provider: "novita" },
  // 新增
  { pattern: /together/i, provider: "together" },
  { pattern: /fire[-_ ]?works/i, provider: "fireworks" },
  { pattern: /replicate/i, provider: "replicate" },
  { pattern: /ollama/i, provider: "ollama" },
  { pattern: /open[-_ ]?router/i, provider: "openrouter" },
  { pattern: /hugging[-_ ]?face|hf\b/i, provider: "huggingface" },
  { pattern: /bed[-_ ]?rock/i, provider: "bedrock" },
  { pattern: /\baws\b/i, provider: "aws" },
  { pattern: /azure/i, provider: "azure" },
  { pattern: /\blambda\b/i, provider: "lambda" },
  { pattern: /cerebras/i, provider: "cerebras" },
  { pattern: /samba[-_ ]?nova/i, provider: "sambanova" },
  { pattern: /deep[-_ ]?infra/i, provider: "deepinfra" },
  { pattern: /\bfal\b/i, provider: "fal" },
  { pattern: /eleven[-_ ]?labs/i, provider: "elevenlabs" },
  { pattern: /haiper/i, provider: "haiper" },
  { pattern: /viggle/i, provider: "viggle" },
  { pattern: /tripo/i, provider: "tripo" },
  { pattern: /sense[-_ ]?nova|商汤/i, provider: "sensenova" },
  { pattern: /tian[-_ ]?gong|天工/i, provider: "tiangong" },
  { pattern: /sky[-_ ]?work/i, provider: "skywork" },
  { pattern: /intern[-_ ]?lm|书生/i, provider: "internlm" },
  { pattern: /jina/i, provider: "jina" },
  { pattern: /voyage/i, provider: "voyage" },
  { pattern: /coze|扣子/i, provider: "coze" },
  { pattern: /dify/i, provider: "dify" },
  { pattern: /nano[-_ ]?banana/i, provider: "nanobanana" },
  { pattern: /ai[-_ ]?21|jamba|jurassic/i, provider: "ai21" },
  { pattern: /ai[-_ ]?360|360智脑|奇虎/i, provider: "ai360" },
  { pattern: /chat[-_ ]?glm/i, provider: "chatglm" },
  { pattern: /dall[\-·]?e/i, provider: "dalle" },
  { pattern: /gemma/i, provider: "gemma" },
  { pattern: /rwkv/i, provider: "rwkv" },
  { pattern: /\bnova\b/i, provider: "nova" },
  { pattern: /vertex[-_ ]?ai|vertex/i, provider: "vertexai" },
  { pattern: /cloud[-_ ]?flare|workers[-_ ]?ai/i, provider: "cloudflare" },
  { pattern: /nebius/i, provider: "nebius" },
  { pattern: /hyperbolic/i, provider: "hyperbolic" },
  { pattern: /inception/i, provider: "inception" },
  { pattern: /lepton[-_ ]?ai|lepton/i, provider: "leptonai" },
  { pattern: /friendli/i, provider: "friendli" },
  { pattern: /featherless/i, provider: "featherless" },
  { pattern: /centml/i, provider: "centml" },
  { pattern: /crusoe/i, provider: "crusoe" },
  { pattern: /para[-_ ]?sail/i, provider: "parasail" },
  { pattern: /up[-_ ]?stage|solar/i, provider: "upstage" },
  { pattern: /\btii\b|falcon/i, provider: "tii" },
  { pattern: /snow[-_ ]?flake|arctic/i, provider: "snowflake" },
  { pattern: /inflection/i, provider: "inflection" },
  { pattern: /deep[-_ ]?cogito/i, provider: "deepcogito" },
  { pattern: /aleph[-_ .]?alpha|luminous/i, provider: "alephalpha" },
  { pattern: /nous[-_ ]?research|nous|hermes/i, provider: "nousresearch" },
  { pattern: /dolphin/i, provider: "dolphin" },
  { pattern: /dbrx/i, provider: "dbrx" },
  { pattern: /kolors/i, provider: "kolors" },
  { pattern: /light[-_ ]?ricks|ltx/i, provider: "lightricks" },
  { pattern: /novel[-_ ]?ai|nai/i, provider: "novelai" },
  { pattern: /fish[-_ .]?audio|fish[-_ .]?speech/i, provider: "fishaudio" },
  { pattern: /coqui|xtts/i, provider: "coqui" },
  { pattern: /comfy[-_ ]?ui/i, provider: "comfyui" },
  { pattern: /automatic[-_ ]?1111|a1111|webui/i, provider: "automatic" },
  { pattern: /civit[-_ ]?ai/i, provider: "civitai" },
  { pattern: /model[-_ ]?scope|魔搭/i, provider: "modelscope" },
  { pattern: /bailian|百炼/i, provider: "bailian" },
  { pattern: /x[-_ ]?inference|xinference/i, provider: "xinference" },
  { pattern: /vllm/i, provider: "vllm" },
  { pattern: /lm[-_ .]?studio/i, provider: "lmstudio" },
  { pattern: /base[-_ ]?ten/i, provider: "baseten" },
  // 补齐
  { pattern: /\baya\b/i, provider: "aya" },
  { pattern: /azure[-_ ]?ai/i, provider: "azureai" },
  { pattern: /baidu|百度/i, provider: "baidu" },
  { pattern: /\bbfl\b|black[-_ .]?forest/i, provider: "bfl" },
  { pattern: /bria[-_ ]?ai|bria/i, provider: "briaai" },
  { pattern: /burn[-_ ]?cloud/i, provider: "burncloud" },
  { pattern: /deep[-_ ]?ai/i, provider: "deepai" },
  { pattern: /deep[-_ ]?mind/i, provider: "deepmind" },
  { pattern: /essential[-_ ]?ai/i, provider: "essentialai" },
  { pattern: /glmv/i, provider: "glmv" },
  { pattern: /google[-_ ]?cloud|gcp/i, provider: "googlecloud" },
  { pattern: /hedra/i, provider: "hedra" },
  { pattern: /iflytek[-_ ]?cloud|讯飞云/i, provider: "iflytekcloud" },
  { pattern: /infermatic/i, provider: "infermatic" },
  { pattern: /infini[-_ ]?gence|无问芯穹/i, provider: "infinigence" },
  { pattern: /kwai[-_ ]?kat|可图/i, provider: "kwaikat" },
  { pattern: /kwai[-_ ]?pilot/i, provider: "kwaipilot" },
  { pattern: /llava/i, provider: "llava" },
  { pattern: /llm[-_ ]?api/i, provider: "llmapi" },
  { pattern: /long[-_ ]?cat/i, provider: "longcat" },
  { pattern: /lovart/i, provider: "lovart" },
  { pattern: /monica/i, provider: "monica" },
  { pattern: /morph/i, provider: "morph" },
  { pattern: /my[-_ ]?shell/i, provider: "myshell" },
  { pattern: /open[-_ ]?chat/i, provider: "openchat" },
  { pattern: /open[-_ .]?web[-_ ]?ui/i, provider: "openwebui" },
  { pattern: /\bpalm\b/i, provider: "palm" },
  { pattern: /phind/i, provider: "phind" },
  { pattern: /player[-_ ]?2/i, provider: "player2" },
  { pattern: /\bpoe\b/i, provider: "poe" },
  { pattern: /pollinations/i, provider: "pollinations" },
  { pattern: /ppio|派欧/i, provider: "ppio" },
  { pattern: /qing[-_ ]?yan|清言/i, provider: "qingyan" },
  { pattern: /soph[-_ ]?net/i, provider: "sophnet" },
  { pattern: /state[-_ ]?cloud/i, provider: "statecloud" },
  { pattern: /straico/i, provider: "straico" },
  { pattern: /stream[-_ ]?lake/i, provider: "streamlake" },
  { pattern: /sub[-_ ]?model/i, provider: "submodel" },
  { pattern: /\bsync\b/i, provider: "sync" },
  { pattern: /targon/i, provider: "targon" },
  { pattern: /topaz[-_ ]?labs|topaz/i, provider: "topazlabs" },
  { pattern: /turix/i, provider: "turix" },
  { pattern: /udio/i, provider: "udio" },
  { pattern: /workers[-_ ]?ai/i, provider: "workersai" },
  { pattern: /xiaomi[-_ ]?mimo|小米mimo/i, provider: "xiaomimimo" },
  { pattern: /xuan[-_ ]?yuan|轩辕/i, provider: "xuanyuan" },
  { pattern: /yandex/i, provider: "yandex" },
  { pattern: /yuan[-_ ]?bao|元宝/i, provider: "yuanbao" },
  { pattern: /zero[-_ ]?one|零一/i, provider: "zeroone" },
  { pattern: /new[-_ ]?api/i, provider: "newapi" },
  { pattern: /npl[-_ ]?cloud/i, provider: "nplcloud" },
];
